### ISSUE TITLE
Nice finding

### ISSUE THREAD

**Issue by mhdzumair** [nopcorn/DuckDuckC2#1]
i've been using duckduckgo image proxy url to serve https image link to stremio from a http [!Ref](https://github.com/mhdzumair/tamilyogi_stremio_addon/blob/86fd339da461277840d7bab2069b800e53571019/scrap.py#L61). I wonder why they allow this in the first place, So came across your article. Thanks.

**Comment by nopcorn** [comment]
Glad you enjoyed the research!
